# Generated by Django 2.1.5 on 2019-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191115_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Алиас'),
        ),
    ]
